<div class="row">
  <div class="col-lg-8">
    <h5 class="page-header">Select Design</h5>
    <?php
    for($i = 0; $i < 12; $i++){
      ?>
      <div class="col-lg-2">
        <center>
          <img class='img-responsive' id='myOne' src='assets/img/catelog/cat2.jpg' alt=''>
          <p><small>Monaco</small><br/> Ghc. 20</p>
        </center>
      </div>
      <?php
    }
    ?>
  </div>
  <div class="col-lg-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <img class="wks-img" src="assets/img/catelog/cat2.jpg">
      </div>
    </div>
  </div>
  <div class="col-lg-12">
    <hr>
    <a href="#mes" data-toggle="tab" class="btn btn-danger"> Next </a>
    <hr>
  </div>
</div>
