<div class="row">
  <div class="col-lg-6">
    <h5 class="page-header">Select Mesurement</h5>
    <p>Enter youru measurement profile to get your dress ready and good.
      Our tailors can make your dress fit your body as stated in the profile or send us a dress.</p>
    <div class="panel-group" id="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
        <h5 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#shirt">
            Men Shirt <i class="fa fa-chevron-down pull-right"></i><br />
            <small>Take measurement for mens shirt</small>
          </a>
        </h5>
        </div>
        <div id="shirt" class="panel-collapse collapse in">
          <div class="panel-body">

          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
        <h5 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#women">
            Women <i class="fa fa-chevron-down pull-right"></i><br />
            <small>Take measurement for womens dress</small>
          </a>
        </h5>
        </div>
        <div id="women" class="panel-collapse collapse ">
          <div class="panel-body">

          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
        <h5 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#child">
            Children <i class="fa fa-chevron-down pull-right"></i><br />
            <small>Provide Measurement for kids wear</small>
          </a>
        </h5>
        </div>
        <div id="child" class="panel-collapse collapse">
          <div class="panel-body">

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
