
<div class="row">
  <div class="col-lg-5">
    <h5 class="page-header">Select Mesurement</h5>
    <p>
      Enter your measurement profile to get your dress ready and good.
      Our tailors can make your dress fit your body as stated in the profile.
    </p>
    <form class="form-horizontal">
      <div class="form-group">
        <div class="col-lg-6">
          <input class="form-control" type="text" placeholder="Fabric Code" disabled>
        </div>
        <div class="col-lg-6">
          <input class="form-control" type="text" placeholder="Design Code" disabled>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-6">
          <input class="form-control" type="text" placeholder="Enter Size">
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-6">
          <select class="form-control">
            <option>--- Service For ---</option>
            <option> Man </option>
            <option> Women </option>
            <option> Boy </option>
            <option> Girl </option>
          </select>
        </div>
        <div class="col-lg-6">
          <select class="form-control">
            <option>--- Service Type ---</option>
            <option> Express </option>
            <option> Standard </option>
          </select>
        </div>
      </div>
    </form>
  </div>
  <div class="col-lg-7">
    <h5 class="page-header">Mesurement Chart</h5>

    <div class="row">
      <div class="col-lg-12">
        <h6>For Women</h6>
        <table class="panel panel-default table table-bordered">
          <thead class="panel-heading">
            <tr>
              <th>SIZE</th>
              <th>FOR USA</th>
              <th>FOR UK</th>
              <th>EUROPE</th>
              <th class="text-center">BUST <br>INCHES | CM</th>
              <th class="text-center">NATURAL WAIST <br>INCHES | CM</th>
              <th class="text-center">WAIST <br>INCHES | CM</th>
            </tr>
          </thead>
          <tbody class="panel-body">
            <tr>
              <td>XS</td>
              <td>0-2</td>
              <td>4-6</td>
              <td>32-34</td>
              <td class="text-center">32-34 | 82-85</td>
              <td class="text-center">25-26 | 63-66</td>
              <td class="text-center">36-37 | 91-94</td>
            </tr>
            <tr>
              <td>S</td>
              <td>2-4</td>
              <td>6-8</td>
              <td>34-36</td>
              <td class="text-center">34-36 | 86-89</td>
              <td class="text-center">36-37 | 66-69</td>
              <td class="text-center">37-38 | 94-96</td>
            </tr>
            <tr>
              <td>M</td>
              <td>6-8</td>
              <td>8-10</td>
              <td>38-40</td>
              <td class="text-center">36-38 | 89-91</td>
              <td class="text-center">28-29 | 70-73</td>
              <td class="text-center">39-40 | 97-101</td>
            </tr>
            <tr>
              <td>L</td>
              <td>8-10</td>
              <td>12-14</td>
              <td>40-42</td>
              <td class="text-center">38-40 | 91-94</td>
              <td class="text-center">29-30 | 73-76</td>
              <td class="text-center">40-41 | 102-104</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <h6>For Men</h6>
        <table class="panel panel-default table table-bordered">
          <thead class="panel-heading">
            <tr>
              <th>SIZE</th>
              <th>FOR USA</th>
              <th>FOR UK</th>
              <th>EUROPE</th>
              <th class="text-center">BUST <br>INCHES | CM</th>
              <th class="text-center">NATURAL WAIST <br>INCHES | CM</th>
              <th class="text-center">WAIST <br>INCHES | CM</th>
            </tr>
          </thead>
          <tbody class="panel-body">
            <tr>
              <td>XS</td>
              <td>0-2</td>
              <td>4-6</td>
              <td>32-34</td>
              <td class="text-center">32-34 | 82-85</td>
              <td class="text-center">25-26 | 63-66</td>
              <td class="text-center">36-37 | 91-94</td>
            </tr>
            <tr>
              <td>S</td>
              <td>2-4</td>
              <td>6-8</td>
              <td>34-36</td>
              <td class="text-center">34-36 | 86-89</td>
              <td class="text-center">36-37 | 66-69</td>
              <td class="text-center">37-38 | 94-96</td>
            </tr>
            <tr>
              <td>M</td>
              <td>6-8</td>
              <td>8-10</td>
              <td>38-40</td>
              <td class="text-center">36-38 | 89-91</td>
              <td class="text-center">28-29 | 70-73</td>
              <td class="text-center">39-40 | 97-101</td>
            </tr>
            <tr>
              <td>L</td>
              <td>8-10</td>
              <td>12-14</td>
              <td>40-42</td>
              <td class="text-center">38-40 | 91-94</td>
              <td class="text-center">29-30 | 73-76</td>
              <td class="text-center">40-41 | 102-104</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <h6>For Children</h6>
        <table class="panel panel-default table table-bordered">
          <thead class="panel-heading">
            <tr>
              <th>SIZE</th>
              <th>FOR USA</th>
              <th>FOR UK</th>
              <th>EUROPE</th>
              <th class="text-center">BUST <br>INCHES | CM</th>
              <th class="text-center">NATURAL WAIST <br>INCHES | CM</th>
              <th class="text-center">WAIST <br>INCHES | CM</th>
            </tr>
          </thead>
          <tbody class="panel-body">
            <tr>
              <td>XS</td>
              <td>0-2</td>
              <td>4-6</td>
              <td>32-34</td>
              <td class="text-center">32-34 | 82-85</td>
              <td class="text-center">25-26 | 63-66</td>
              <td class="text-center">36-37 | 91-94</td>
            </tr>
            <tr>
              <td>S</td>
              <td>2-4</td>
              <td>6-8</td>
              <td>34-36</td>
              <td class="text-center">34-36 | 86-89</td>
              <td class="text-center">36-37 | 66-69</td>
              <td class="text-center">37-38 | 94-96</td>
            </tr>
            <tr>
              <td>M</td>
              <td>6-8</td>
              <td>8-10</td>
              <td>38-40</td>
              <td class="text-center">36-38 | 89-91</td>
              <td class="text-center">28-29 | 70-73</td>
              <td class="text-center">39-40 | 97-101</td>
            </tr>
            <tr>
              <td>L</td>
              <td>8-10</td>
              <td>12-14</td>
              <td>40-42</td>
              <td class="text-center">38-40 | 91-94</td>
              <td class="text-center">29-30 | 73-76</td>
              <td class="text-center">40-41 | 102-104</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
