<div class="row">
  <div class="col-lg-8">
    <h5 class="page-header">View Summary</h5>
    <table class="table table-hover table-bordered panel panel-default">
      <thead class="panel-heading">
        <tr class="panel-title">
          <th>Item No.</th>
          <th>Item</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Total Cost</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="panel-body">
        <tr>
          <td>fr1234</td>
          <td><img src="assets/img/fabric/fbr3.jpg" class="tb-img"></td>
          <td>20.00</td>
          <td><input type="number" class="form-control"></td>
          <td>20.00</td>
          <td>
            <a href="#" class="btn btn-warning btn-xs"><i class="fa fa-times-circle-o"></i> Remove</a>
          </td>
        </tr>
        <tr>
          <td>de1234</td>
          <td><img src='assets/img/catelog/cat2.jpg' class="tb-img"></td>
          <td>20.00</td>
          <td><input type="number" class="form-control"></td>
          <td>20.00</td>
          <td>
            <a href="#" class="btn btn-warning btn-xs"><i class="fa fa-times-circle-o"></i> Remove</a>
          </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td><h5><b>Estimated Cost</b></h5></td>
          <td><h5><b>40.00</b></h5></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td><h4><b>Total</b></h4></td>
          <td><h4><b>40.00</b></h4></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-lg-4">
    <h5 class="page-header">Payment Method</h5>
    <a href="#mes" data-toggle="tab" class="btn btn-success"> Check out <i class="fa fa-check"></i></a>
  </div>
</div>
