<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-bar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.php"><img src="assets/img/logo.png"></a>
    </div>
    <div class="collapse navbar-collapse" id="menu-bar">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="index.php">Home</a>
        </li>
        <li>
          <a href="#">About</a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Store <b class="caret"></b> </a>
          <ul class="dropdown-menu">
            <li><a href="store.php">Clothing</a></li>
            <li><a href="#">Accessoriesk</a></li>
          </ul>
        </li>
        <li>
          <a href="workshop.php">Workshop</a>
        </li>
        <li>
          <a href="#">How it works</a>
        </li>
        <li>
          <a href="#">Contact</a>
        </li>
        <li>
          <a href="#"><i class="fa fa-search"></i></a>
        </li>
        <li>
          <a href="#"><i class="fa fa-shopping-cart"></i> <span class="badge">0</span></a>
        </li>
        <a href="#" class="btn btn-danger navbar-btn">Create an Account</a>
      </ul>
    </div>
  </div>
</nav>
