<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline">
          <li>
            <a href="#">Home</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-caret-right"></i> About</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-caret-right"></i> Store</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-caret-right"></i> Workshop</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-caret-right"></i> How it works</a>
          </li>
          <li>
            <a href="#"><i class="fa fa-caret-right"></i> Contact</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline">
          <li>
            Copyright (c) 2017 Hadassa All Rights Reserved.
          </li>
          <li>
            <a href="#">Terms of Service</a>
          </li>
          <li>
            <a href="#">Privacy Policy</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
