<!-- Half Page Image Background Carousel Header -->
<header id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
      <li data-target="#myCarousel" data-slide-to="5"></li>
  </ol>

  <!-- Wrapper for Slides -->
  <div class="carousel-inner">
    <div class="item active">
      <div class="fill" style="background-image:url('assets/img/sliders/slider1.jpg');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('assets/img/sliders/slider2.jpg');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('assets/img/sliders/slider3.jpg');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('assets/img/sliders/slider4.jpg');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('assets/img/sliders/slider5.jpg');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('assets/img/sliders/slider6.jpg');"></div>
    </div>
  </div>

</header>
