<!-- Half Page Image Background Carousel Header -->
<header id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for Slides -->
  <div class="carousel-inner">
    <div class="item active">
      <div class="fill" style="background-image:url('assets/img/sliders/slide1.jpg');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('assets/img/sliders/slide2.jpg');"></div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('assets/img/sliders/slide3.jpg');"></div>
    </div>
  </div>

</header>
