<div class="navbar navbar-inverse navbar-static-top hidden-md hidden-sm hidden-xs" role="navigation">
  <div class="container">
    <ul class="nav navbar-nav">
      <li>
        <a href="#"><i class="fa fa-map-marker"></i> NTA Poasi Industrial Area</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-phone"></i> +233 200 000 000</a>
      </li>
      <li>
        <a href="#"><i class="fa fa-envelope"></i> info@hadassa.com</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="https://www.facebook.com/Ajo-social-entrepreneurship-network-1342072225834966/"><i class="fa fa-facebook"></i></a>
      </li>
      <li>
        <a href="https://twitter.com/ajo_2016"><i class="fa fa-twitter"></i></a>
      </li>
      <li>
        <a href="https://twitter.com/ajo_2016"><i class="fa fa-linkedin"></i></a>
      </li>
      <li>
        <a href="https://twitter.com/ajo_2016"><i class="fa fa-youtube"></i></a>
      </li>
      <li>
        <a href="https://plus.google.com/u/0/103308040084371110938"><i class="fa fa-google-plus-circle"></i></a>
      </li>
    </ul>
  </div>
</div>
